package roj.http.server.auto;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Specifies the MIME type for responses generated by the annotated method or class.
 * Affects string-returning handlers but not those explicitly returning {@link roj.http.server.Content}.
 *
 * <p><strong>Example:</strong></p>
 * <pre>{@code
 * @Mime("application/json")
 * @GET("/data")
 * public String getData() { return "{\"key\":\"value\"}"; }
 * }</pre>
 *
 * @author Roj234
 * @since 2023/2/5 11:35
 * @see Route
 * @see roj.http.server.Content
 */
@Retention(RetentionPolicy.CLASS)
@Target({ElementType.METHOD, ElementType.TYPE})
public @interface Mime {
	/**
	 * The MIME type string (e.g., "application/json").
	 *
	 * @return the MIME type
	 */
	String value();
}