type: MAP
properties:
  version:
    type: STRING
    pattern: MCMake \d+\.\d+\.\d+
  日志配置文件:
    type: STRING
    required: false
  自动编译防抖:
    type: INTEGER
    default: 250
    min: 50
    max: 5000
    constraints: |-
      return value.asInt() % 10 != 0;
  映射缓存大小:
    type: INTEGER
    default: 15
    min: 0
    max: 100
  工作区:
    default: {}
    type: MAP
    children:
      type: MAP
      properties:
        type:
          type: STRING
  编译器:
    type: MAP
    default: {}
    children:
      type: MAP
      properties:
        type:
          type: STRING
        options:
          type: LIST
          required: false
          children:
            type: STRING
  插件:
    type: MAP
    default: {}