package roj.compiler;

public interface CompilerSpec {
	int ATTR_METHOD_PARAMETERS = 0;
	int ATTR_SOURCE_FILE = 1;
	int ATTR_LINE_NUMBERS = 2;
	int ATTR_LOCAL_VARIABLES = 3;
	int ATTR_INNER_CLASS = 4;
	int ATTR_STACK_FRAME = 5;
	int PRIMITIVE_GENERIC = 6;
	int INTERFACE_INACCESSIBLE_FIELD = 16;
	int ADVANCED_GENERIC_CHECK = 32;
	int KOTLIN_SEMICOLON = 33;
	int DISABLE_RAW_TYPE = 114514;
}