package roj.asm.util.type;

import roj.asm.util.IType;
import roj.text.CharList;

import java.util.*;

/**
 * This file is a part of more items mod (MI)
 * (L) Copyleft 2020-20XX 版权没有, 仿冒不究,如有雷同,纯属活该
 * <p>
 * @author Roj234
 * Filename: null.java
 */
public class SignatureHelper {
    public static void main(String[] args) {
        Signature signature = parse(args[0]);
        System.out.println("toString(): " + signature);
        System.out.println("getSignatureType(): " + signature.getSignatureType());
        System.out.println("toGeneric(): " + signature.toGeneric());
    }

    /**
     * Signatures encode declarations written in the Java programming language that use types outside the type system of the Java Virtual Machine. They support reflection and debugging, as well as compilation when only class files are available.
     * <p>
     * A Java compiler must emit a signature for any class, interface, constructor, method, or field whose declaration uses type variables or parameterized types. Specifically, a Java compiler must emit:
     * <p>
     * A class signature for any class or interface declaration which is either generic, or has a parameterized type as a superclass or superinterface, or both.
     * <p>
     * A method signature for any method or constructor declaration which is either generic, or has a type variable or parameterized type as the return type or a formal parameter type, or has a type variable in a throws clause, or any combination thereof.
     * <p>
     * If the throws clause of a method or constructor declaration does not involve type variables, then a compiler may treat the declaration as having no throws clause for the purpose of emitting a method signature.
     * <p>
     * A field signature for any field, formal parameter, or local variable declaration whose type uses a type variable or a parameterized type.
     * <p>
     * Signatures are specified using a grammar which follows the notation of §4.3.1. In addition to that notation:
     * <p>
     * The syntax [x] on the right-hand side of a production denotes zero or one occurrences of x. That is, x is an optional symbol. The alternative which contains the optional symbol actually defines two alternatives: one that omits the optional symbol and one that includes it.
     * <p>
     * A very long right-hand side may be continued on a second line by clearly indenting the second line.
     * <p>
     * The grammar includes the terminal symbol Identifier to denote the name of a type, field, method, formal parameter, local variable, or type variable, as generated by a Java compiler. Such a name must not contain any of the ASCII characters . ; [ / < > : (that is, the characters forbidden in method names (§4.2.2) and also colon) but may contain characters that must not appear in an identifier in the Java programming language (JLS §3.8).
     * <p>
     * Signatures rely on a hierarchy of nonterminals known as type signatures:
     * <p>
     * A Java type signature represents either a reference type or a primitive type of the Java programming language.
     * <p>
     * JavaTypeSignature:
     * ReferenceTypeSignature
     * BaseType
     * The following production from §4.3.2 is repeated here for convenience:
     * <p>
     * BaseType:
     * (one of)
     * B C D F I J S Z
     * A reference type signature represents a reference type of the Java programming language, that is, a class or interface type, a type variable, or an array type.
     * <p>
     * A class type signature represents a (possibly parameterized) class or interface type. A class type signature must be formulated such that it can be reliably mapped to the binary name of the class it denotes by erasing any type arguments and converting each . character to a $ character.
     * <p>
     * A type variable signature represents a type variable.
     * <p>
     * An array type signature represents one dimension of an array type.
     * <p>
     * ReferenceTypeSignature:
     * ClassTypeSignature
     * TypeVariableSignature
     * ArrayTypeSignature
     * ClassTypeSignature:
     * L [PackageSpecifier] SimpleClassTypeSignature {ClassTypeSignatureSuffix} ;
     * PackageSpecifier:
     * Identifier / {PackageSpecifier}
     * SimpleClassTypeSignature:
     * Identifier [TypeArguments]
     * TypeArguments:
     * < TypeArgument {TypeArgument} >
     * TypeArgument:
     * [WildcardIndicator] ReferenceTypeSignature
     * *
     * WildcardIndicator:
     * +
     * -
     * ClassTypeSignatureSuffix:
     * . SimpleClassTypeSignature
     * TypeVariableSignature:
     * T Identifier ;
     * ArrayTypeSignature:
     * [ JavaTypeSignature
     * A class signature encodes type information about a (possibly generic) class declaration. It describes any type parameters of the class, and lists its (possibly parameterized) direct superclass and direct superinterfaces, if any. A type parameter is described by its name, followed by any class bound and interface bounds.
     * <p>
     * ClassSignature:
     * [TypeParameters] SuperclassSignature {SuperinterfaceSignature}
     * TypeParameters:
     * < TypeParameter {TypeParameter} >
     * TypeParameter:
     * Identifier ClassBound {InterfaceBound}
     * ClassBound:
     * : [ReferenceTypeSignature]
     * InterfaceBound:
     * : ReferenceTypeSignature
     * SuperclassSignature:
     * ClassTypeSignature
     * SuperinterfaceSignature:
     * ClassTypeSignature
     * A method signature encodes type information about a (possibly generic) method declaration. It describes any type parameters of the method; the (possibly parameterized) types of any formal parameters; the (possibly parameterized) return type, if any; and the types of any exceptions declared in the method's throws clause.
     * <p>
     * MethodSignature:
     * [TypeParameters] ( {JavaTypeSignature} ) Result {ThrowsSignature}
     * Result:
     * JavaTypeSignature
     * VoidDescriptor
     * ThrowsSignature:
     * ^ ClassTypeSignature
     * ^ TypeVariableSignature
     * The following production from §4.3.3 is repeated here for convenience:
     * <p>
     * VoidDescriptor:
     * V
     * Due to compiler-generated artifacts, the method signature of a method may not correspond exactly to the method descriptor of the method (§4.3.3). In particular, the number of formal parameter types in the method signature may be less than the number of parameter descriptors in the method descriptor.
     * <p>
     * A field signature encodes the (possibly parameterized) type of a field, formal parameter, or local variable declaration.
     * <p>
     * FieldSignature:
     * ReferenceTypeSignature
     */

    public static Signature parse(String generic) {
        int i = 0;

        Map<String, Collection<Generic>> map = new LinkedHashMap<>();

        if (generic.charAt(0) == '<') {
            i = 1;

            CharList tmp = new CharList();

            outer:
            while (i < generic.length()) {
                char cr = generic.charAt(i++);
                switch (cr) {
                    case ':': {
                        String key = tmp.toString();
                        tmp.clear();
                        Collection<Generic> collection = new LinkedList<>();

                        boolean first = true;

                        while (first || hasNext(generic, i)) {
                            Object[] arr = getSignatureValue(generic, i, true, false, false);
                            collection.add((Generic) arr[0]);
                            i = (int) arr[1];
                            first = false;
                        }

                        map.put(key, collection);
                        continue;
                    }
                    case '>':
                        break outer;
                    default:
                        tmp.append(cr);
                }
            }
        }

        List<IType> params = new ArrayList<>();
        boolean isMethod = generic.charAt(i) == '(';
        if (isMethod) {
            i++;
        }

        List<IType> exceptions = new ArrayList<>();

        boolean returnVal = false;
        while (i < generic.length()) {
            switch (generic.charAt(i)) {
                case '^':
                    if (returnVal) {
                        i++;
                        Object[] arr = getSignatureValue(generic, i, false, false, false);

                        IType value = (IType) arr[0];
                        i = (int) arr[1];

                        exceptions.add(value);

                        continue;
                    } else {
                        throw new IllegalArgumentException("[" + (i) + "(" + generic.charAt(i) + ")]" + generic);
                    }
                case ')':
                    if (!returnVal) {
                        i++;
                        returnVal = true;
                        break;
                    } else {
                        throw new IllegalArgumentException("[" + (i) + "(" + generic.charAt(i) + ")]" + generic);
                    }
            }

            Object[] arr = getSignatureValue(generic, i, false, true, false);

            IType value = (IType) arr[0];
            i = (int) arr[1];

            params.add(value);
        }

        return new Signature(map, params, isMethod, exceptions);
    }

    private static boolean hasNext(String generic, int i) {
        switch (generic.charAt(i++)) {
            case ':':
                return true;
            case 'L':
            case 'T':
                return generic.charAt(i) != ':';
            case '>':
            default:
                return false;
        }
    }

    @SuppressWarnings("fallthrough")
    public static Object[] getSignatureValue(String s, int i, boolean checkItf, boolean canBePrimitive, boolean isSubClass) {
        CharList tmp = new CharList();

        int arrayLevel = 0;
        byte subClass = 0;

        byte cat;
        if (!isSubClass) {
            switch (s.charAt(i)) {
                case '+':
                    subClass = Generic.TYPE_EXTENDS;
                    i++;
                    break;
                case '-':
                    subClass = Generic.TYPE_SUPERS;
                    i++;
                    break;
                case '[':
                    while (s.charAt(i) == '[') {
                        arrayLevel++;
                        i++;
                    }
            }

            final char c = s.charAt(i);
            if (canBePrimitive) {
                if (NativeType.isValidate(c) && c != NativeType.CLASS) {
                    return new Object[]{new Type(c, arrayLevel), i + 1};
                }
            }

            switch (c) {
                case '*': {
                    Generic value = new Generic(Generic.CLASS, "*", arrayLevel, subClass);
                    return new Object[]{value, i + 1};
                }
                case 'T':
                    cat = Generic.TYPE_PARAM;
                    break;
                case 'L':
                    cat = Generic.CLASS;
                    break;
                case ':':
                    cat = Generic.INTERFACE;
                    if (checkItf) {
                        if (s.charAt(++i) == 'L')
                            break;
                    }
                default:
                    throw new IllegalArgumentException("[" + (i) + "(" + s.charAt(i) + ")]" + s);
            }
            i++;
        } else {
            cat = Generic.SUB_CLASS;
        }

        boolean shouldFindNext = false;

        while (i < s.length()) {
            char c1 = s.charAt(i++);
            if (c1 == ';' || c1 == '<') {
                i--;
                if (c1 == '<')
                    shouldFindNext = true;
                break;
            }
            tmp.append(c1);
        }

        if (tmp.length() == 0) {
            throw new IllegalArgumentException("[" + (i) + "(" + s.charAt(i) + ")]" + s);
        }

        Generic value = new Generic(cat, tmp.toString(), arrayLevel, subClass);

        if (shouldFindNext) {
            i++;
            while (i < s.length() && s.charAt(i) != '>') {
                Object[] arr = getSignatureValue(s, i, checkItf, canBePrimitive, isSubClass);
                i = (Integer) arr[1];
                value.addChild((IType) arr[0]);
            }
        }
        if (s.charAt(i) != ';') {
            if (s.charAt(i) != '>') {
                throw new IllegalArgumentException("[" + (i) + "(" + s.charAt(i) + ")]" + s);
            } else if (s.charAt(++i) != ';') {
                if (s.charAt(i) != '.')
                    throw new IllegalArgumentException("[" + (i) + "(" + s.charAt(i) + ")]" + s);
                else {
                    Object[] subClass1 = getSignatureValue(s, i + 1, checkItf, false, true);
                    value.subClass = (Generic) subClass1[0];
                    i = (int) subClass1[1] - 1;
                }
            }
        }
        i++;

        return new Object[]{value, i};
    }
}
